FluentHub/App.xaml, FluentHub/App.xaml.cs, FluentHub/Dialogs/SetupDialog.xaml, FluentHub/Dialogs/SetupDialog.xaml.cs, FluentHub/FluentHub.csproj, FluentHub/Helpers/LanguageColorHelpers.cs, FluentHub/Models/Items/RepoListItem.cs, FluentHub/Models/RepoListItem.cs, FluentHub/Services/Auth/RequestAuthorization.cs, FluentHub/Services/OctokitEx/UserPinnedItems.cs, FluentHub/ViewModels/UserPages/ActivitiesViewModel.cs, FluentHub/ViewModels/UserPages/RepositoriesViewModel.cs, FluentHub/Views/UserPages/Activities.xaml, FluentHub/Views/UserPages/Activities.xaml.cs, FluentHub/Views/UserPages/ProfilePage.xaml, FluentHub/Views/UserPages/Repositories.xaml, FluentHub/Views/UserPages/Repositories.xaml.cs, FluentHub/Views/WelcomePage.xaml
None
- Fix class name.
- Update welcome page
- Force web authentication.
- Rename some statements.
**Validation**
=> Add pinned repos block on user profile page

FluentHub/Views/UserPages/ProfilePage.xaml.cs
- Closes #3 
- Replace Uri class with UriBuilder class to rebuild URI.
**Validation**
=> Fixe an issue with an URL that don't contain the schema

FluentHub/FluentHub.csproj, FluentHub/Models/Items/ProfileBlockItem.cs, FluentHub/Services/OctokitEx/DevProgramMember.cs, FluentHub/ViewModels/UserPages/ProfilePageViewModel.cs, FluentHub/Views/MainPage.xaml, FluentHub/Views/MainPage.xaml.cs, FluentHub/Views/UserPages/Activities.xaml, FluentHub/Views/UserPages/ProfilePage.xaml, FluentHub/Views/UserPages/ProfilePage.xaml.cs, README.md
None
As title of this PR
**Validation**
=> Update the UI of the user profile page

FluentHub/Views/UserPages/ProfilePage.xaml.cs
https://github.com/fluenthub-uwp/FluentHub/issues/15#issuecomment-1021315111
As title of this PR
**Validation**
Reproduced:
=> Fix null check of the user page company profile element

FluentHub/FluentHub.csproj, FluentHub/UserControls/Block/RepoBlock.xaml, FluentHub/UserControls/Block/RepoBlock.xaml.cs, FluentHub/Views/MainPage.xaml.cs, FluentHub/Views/RepoPages/OverviewPage.xaml, FluentHub/Views/RepoPages/OverviewPage.xaml.cs, FluentHub/Views/UserPages/OverviewPage.xaml
Items resolved / related issues by this PR.
- Closes #23
Add details of changes here.
- Home button in the toolbar is available.
- Fixed bad sizing of Pinned repositories cards in the Profile View.
- Update star button visiblity
**Validation**
Fix sizing and wrap repo name and repo description:
=> Add repository overview page

FluentHub/App.xaml, FluentHub/FluentHub.csproj, FluentHub/Models/Items/IssueListItem.cs, FluentHub/ResourceDictionaries/ClearButtonStyle.xaml, FluentHub/ResourceDictionaries/LinkLikeButtonStyle.xaml, FluentHub/UserControls/Block/CommentBlock.xaml, FluentHub/UserControls/Block/CommentBlock.xaml.cs, FluentHub/UserControls/Block/RepoBlock.xaml, FluentHub/UserControls/CodeFlyout.xaml, FluentHub/UserControls/CodeFlyout.xaml.cs, FluentHub/UserControls/CustomTabView.xaml, FluentHub/UserControls/GitCloneFlyout.xaml, FluentHub/UserControls/GitCloneFlyout.xaml.cs, FluentHub/UserControls/Labels/StateLabel.xaml, FluentHub/UserControls/Labels/StateLabel.xaml.cs, FluentHub/UserControls/SettingsBlockControl.xaml, FluentHub/UserControls/SettingsDisplayControl.xaml, FluentHub/ViewModels/RepoPages/PullRequestListViewModel.cs, FluentHub/Views/RepoPages/CodePage.xaml, FluentHub/Views/RepoPages/CodePage.xaml.cs, FluentHub/Views/RepoPages/IssueListPage.xaml, FluentHub/Views/RepoPages/IssuePage.xaml, FluentHub/Views/RepoPages/IssuePage.xaml.cs, FluentHub/Views/RepoPages/OverviewPage.xaml, FluentHub/Views/RepoPages/OverviewPage.xaml.cs, FluentHub/Views/RepoPages/PullRequestListPage.xaml, FluentHub/Views/RepoPages/PullRequestListPage.xaml.cs, FluentHub/Views/RepoPages/Settings.xaml, FluentHub/Views/UserPages/OverviewPage.xaml
- Related #30
- Closes #31
- Closes #26
*cannot describe about those changes. there are so many changes.*
**Validation**
=> Update repository pages 2

FluentHub/Views/AppSettings/AboutPage.xaml, FluentHub/Views/AppSettings/AboutPage.xaml.cs
=> Ability to open the logs folder

Privacy Policy.md
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...
Add details of changes here.
- Added...
- Fixed...
**Validation**
Add screenshots here.
=> Create Privacy Policy.md

FluentHub/FluentHub.csproj, FluentHub/MultilingualResources/FluentHub.zh-CN.xlf, FluentHub/Strings/zh-CN/Resources.resw
Update Simplified Translation in dev
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...
Add details of changes here.
目前在FluentHub Dev提供了一次简单的简体中文翻译，待到您的项目完成之后我再进行其余剩下的翻译
FluentHub Dev currently provides a simple simplified Chinese translation, I will do the rest after your project is completed
- Added...
- Fixed...
**Validation**
- [×] Built and ran the app
Add screenshots here.
=> Add zh-CN(Simplified Chinese) Translation

FluentHub/FluentHub.csproj, FluentHub/MultilingualResources/FluentHub.pt-BR.xlf, FluentHub/Strings/pt-BR/Resources.resw
Added Portuguese (Brazil) translation
**Validation**
Add screenshots here.
=> Add PT-BR translation

src/FluentHub/Views/Home/UserHomePage.xaml
- Closes 
- Related
Make UserHomePage more responsive. Use VisualState to update the NavigationView.PaneDisplayMode to Auto or Top based on Window size
**Validation**
Current|New
:---:|:---:
=> Make UserHomePage more responsive

src/FluentHub/Views/MainPage.xaml, src/FluentHub/Views/MainPage.xaml.cs
- Closes #100
Shortcut | Description | Status
:-|:-|:-:
`Ctrl` + `T` | Opens a new tab | ✅
`Ctrl` + `W` | Closes the current tab | ✅
`Ctrl` + `Tab` | Go to the next tab | ✅
`Ctrl` + `Shift` + `Tab` | Go to the previous tab | ✅
`Alt` + `Left` | Navigate back | ✅
`Alt` + `Right` | Navigate forward | ✅
`Back` (mouse) | Navigate back | ✅
`Forward` (mouse) | Navigate forward | ✅
`F5` | Refresh the page | ❌
=> Add keyboard shortcuts

src/FluentHub.Octokit/FluentHub.Octokit.csproj, src/FluentHub.Octokit/Helpers/ColorHelper.cs, src/FluentHub.Octokit/Models/CalendarDay.cs, src/FluentHub.Octokit/Models/ContributionCalender.cs, src/FluentHub.Octokit/Queries/Users/ActivityQueries.cs, src/FluentHub/FluentHub.csproj, src/FluentHub/UserControls/Blocks/UserContributionGraph.xaml, src/FluentHub/UserControls/Blocks/UserContributionGraph.xaml.cs, src/FluentHub/ViewModels/UserControls/Blocks/UserContributionGraphViewModel.cs, src/FluentHub/ViewModels/Users/OverviewViewModel.cs, src/FluentHub/Views/Users/OverviewPage.xaml, src/FluentHub/Views/Users/OverviewPage.xaml.cs
- Added user's contribution graph
=> Added user's contribution graph

.github/stale.yml
=> Added github stale bot

README.md
- Fixes #132 
- Fixed the discord link not redirecting to the server
=> Fixed the Discord invite link

README.md, src/FluentHub.Octokit/FluentHub.Octokit.csproj, src/FluentHub.Octokit/Models/Content.cs, src/FluentHub.Octokit/Queries/Repositories/CommitQueries.cs, src/FluentHub.Octokit/Queries/Repositories/ContentQueries.cs, src/FluentHub/App.xaml.cs, src/FluentHub/FluentHub.csproj, src/FluentHub/Models/TreeLayoutPageModel.cs, src/FluentHub/ResourceDictionaries/DefaultGridSplitterStyle.xaml, src/FluentHub/UserControls/Blocks/FileContentBlock.xaml, src/FluentHub/UserControls/Blocks/FileContentBlock.xaml.cs, src/FluentHub/ViewModels/Repositories/Codes/Layouts/TreeLayoutViewModel.cs, src/FluentHub/ViewModels/UserControls/Blocks/FileContentBlockViewModel.cs, src/FluentHub/Views/Repositories/Codes/CodePage.xaml.cs, src/FluentHub/Views/Repositories/Codes/Layouts/TreeLayoutView.xaml, src/FluentHub/Views/Repositories/Codes/Layouts/TreeLayoutView.xaml.cs
- Closes 
- Added tree layout view
=> Added tree layout view

src/FluentHub/Views/AppSettings/AboutPage.xaml, src/FluentHub/Views/AppSettings/AccountsPage.xaml, src/FluentHub/Views/AppSettings/AppearancePage.xaml, src/FluentHub/Views/AppSettings/CodePreviewPage.xaml, src/FluentHub/Views/MainPage.xaml, src/FluentHub/Views/SignIn/IntroPage.xaml, src/FluentHub/Views/SignIn/SignInPage.xaml
As the title
As the title
_None_
=> Update English: Grammar, Punctuation & Spelling

src/FluentHub/Views/SignIn/SignInPage.xaml
As the title
As the title
_None_
=> Update tiny SPaG mistake

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md
As the title
As the title
_None_
=> Report Templates

.github/PULL_REQUEST_TEMPLATE.md
=> Report Templates v2

src/FluentHub/Views/AppSettings/AboutPage.xaml
None
Added @DeveloperWOW64 as contributor and updated @onein528's name
None
None
=> Added a new collaborator to About page

src/FluentHub.Octokit/Queries/Users/NotificationQueries.cs, src/FluentHub/ViewModels/Repositories/Issues/IssueViewModel.cs, src/FluentHub/ViewModels/Repositories/PullRequests/ConversationViewModel.cs, src/FluentHub/ViewModels/Users/ProfilePageViewModel.cs, src/FluentHub/Views/Repositories/Codes/Layouts/DetailsLayoutView.xaml.cs, src/FluentHub/Views/Repositories/Codes/Layouts/TreeLayoutView.xaml.cs
- Related: None
- Fixed: None
Checks for events before accessing them, prevents NullReferenceException
=> Check events before accessing them (anti-nullreferenceexception)

builds/azure-pipelines-sideload.yml
[skip ci]
- Related: #
- Fixed: #
=> Added Sideload Azure Pipeline

builds/azure-pipelines-release.yml
[skip ci]
- Related: #
- Fixed: #
=> Added Release Azure Pipeline

src/FluentHub.Octokit/Queries/Users/NotificationQueries.cs
None
As in the title
As in the title
None
=> Update grammar in activities page

docs/credentials.md
=> Fix typo in docs

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/tracker.yml, .github/PULL_REQUEST_TEMPLATE.md
=> Update project report templates

CODEOWNERS
=> 📝 Fix CODEOWNERS error

LICENSE, README.md
Updates legal copyright span date to include 2023
=> Update Copyright Span date

src/FluentHub.App/Strings/fr-FR/Resources.resw
- Related: # Translation
- Fixed: # Making french (France) translation
I translate missing french (France) Resource file to actual french.
No assets available.
=> Update French localization resources

src/FluentHub.App/Strings/vi-VN/Resources.resw
- [] Have you built and ran the app?
- Related: #Translation
- Fixed: #Update Vietnamese (Viet Nam) translation
I translated some non-translated line to Vietnamese
=> Update Vietnamese locale

src/FluentHub.App/FluentHub.App.csproj, src/FluentHub.App/app.manifest
- Fixed: #385
Add the missing manifest for DPI configuration to resolve blurry issue.
=> Add missing manifest for DPI config

docs/fix-degital-sig.md
=> Fix: Fixed typo in docs/fix-degital-sig.md

src/FluentHub.App/Strings/fr-FR/Resources.resw
=> Localization: Improved French translations

.github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/spec.yml, .github/PULL_REQUEST_TEMPLATE.md
Removed tasklists from the issue/pr templates.
GitHub have closed the beta for them.
=> GitHub: Remove tasklists from issue templates
